language: php

services:
    - mysql
    - postgresql

env:
    global:
        - COMPOSER_ROOT_VERSION=4.3.x-dev

matrix:
    include:
        - php: 7.1
          env: DB=MYSQL RECIPE_VERSION=~4.3.0 PHPUNIT_TEST=1 PHPCS_TEST=1
        - php: 7.2
          env: DB=PGSQL RECIPE_VERSION=~4.4.0 PHPUNIT_TEST=1
        - php: 7.3
          env: DB=MYSQL RECIPE_VERSION=^4
        - php: 7.4
          env: DB=MYSQL RECIPE_VERSION=^4 PHPUNIT_COVERAGE_TEST=1

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

before_script:
    - phpenv rehash
    - phpenv config-rm xdebug.ini

    - composer validate
    - composer require --no-update silverstripe/recipe-cms:"$RECIPE_VERSION"
    - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:^2.1.0; fi
    - composer install --prefer-source --no-interaction --no-progress --optimize-autoloader --verbose --profile

script:
    - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/; fi
    - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
    - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ *.php; fi

after_success:
    - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -F php; fi
